version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend/web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    depends_on:
      - backend
